// Code generated by go-swagger; DO NOT EDIT.

package voucher_approval_list_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewVoucherApprovalListElementGetParams creates a new VoucherApprovalListElementGetParams object
// with the default values initialized.
func NewVoucherApprovalListElementGetParams() *VoucherApprovalListElementGetParams {
	var ()
	return &VoucherApprovalListElementGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVoucherApprovalListElementGetParamsWithTimeout creates a new VoucherApprovalListElementGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVoucherApprovalListElementGetParamsWithTimeout(timeout time.Duration) *VoucherApprovalListElementGetParams {
	var ()
	return &VoucherApprovalListElementGetParams{

		timeout: timeout,
	}
}

// NewVoucherApprovalListElementGetParamsWithContext creates a new VoucherApprovalListElementGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewVoucherApprovalListElementGetParamsWithContext(ctx context.Context) *VoucherApprovalListElementGetParams {
	var ()
	return &VoucherApprovalListElementGetParams{

		Context: ctx,
	}
}

// NewVoucherApprovalListElementGetParamsWithHTTPClient creates a new VoucherApprovalListElementGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVoucherApprovalListElementGetParamsWithHTTPClient(client *http.Client) *VoucherApprovalListElementGetParams {
	var ()
	return &VoucherApprovalListElementGetParams{
		HTTPClient: client,
	}
}

/*VoucherApprovalListElementGetParams contains all the parameters to send to the API endpoint
for the voucher approval list element get operation typically these are written to a http.Request
*/
type VoucherApprovalListElementGetParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) WithTimeout(timeout time.Duration) *VoucherApprovalListElementGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) WithContext(ctx context.Context) *VoucherApprovalListElementGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) WithHTTPClient(client *http.Client) *VoucherApprovalListElementGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) WithFields(fields *string) *VoucherApprovalListElementGetParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) WithID(id int32) *VoucherApprovalListElementGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the voucher approval list element get params
func (o *VoucherApprovalListElementGetParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *VoucherApprovalListElementGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
