// Code generated by go-swagger; DO NOT EDIT.

package passenger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// NewTravelExpensePassengerPutParams creates a new TravelExpensePassengerPutParams object
// with the default values initialized.
func NewTravelExpensePassengerPutParams() *TravelExpensePassengerPutParams {
	var ()
	return &TravelExpensePassengerPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTravelExpensePassengerPutParamsWithTimeout creates a new TravelExpensePassengerPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTravelExpensePassengerPutParamsWithTimeout(timeout time.Duration) *TravelExpensePassengerPutParams {
	var ()
	return &TravelExpensePassengerPutParams{

		timeout: timeout,
	}
}

// NewTravelExpensePassengerPutParamsWithContext creates a new TravelExpensePassengerPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewTravelExpensePassengerPutParamsWithContext(ctx context.Context) *TravelExpensePassengerPutParams {
	var ()
	return &TravelExpensePassengerPutParams{

		Context: ctx,
	}
}

// NewTravelExpensePassengerPutParamsWithHTTPClient creates a new TravelExpensePassengerPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTravelExpensePassengerPutParamsWithHTTPClient(client *http.Client) *TravelExpensePassengerPutParams {
	var ()
	return &TravelExpensePassengerPutParams{
		HTTPClient: client,
	}
}

/*TravelExpensePassengerPutParams contains all the parameters to send to the API endpoint
for the travel expense passenger put operation typically these are written to a http.Request
*/
type TravelExpensePassengerPutParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.Passenger
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) WithTimeout(timeout time.Duration) *TravelExpensePassengerPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) WithContext(ctx context.Context) *TravelExpensePassengerPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) WithHTTPClient(client *http.Client) *TravelExpensePassengerPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) WithBody(body *models.Passenger) *TravelExpensePassengerPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) SetBody(body *models.Passenger) {
	o.Body = body
}

// WithID adds the id to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) WithID(id int32) *TravelExpensePassengerPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the travel expense passenger put params
func (o *TravelExpensePassengerPutParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TravelExpensePassengerPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
