// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package vat_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLedgerVatTypeSearchParams creates a new LedgerVatTypeSearchParams object
// with the default values initialized.
func NewLedgerVatTypeSearchParams() *LedgerVatTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &LedgerVatTypeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewLedgerVatTypeSearchParamsWithTimeout creates a new LedgerVatTypeSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLedgerVatTypeSearchParamsWithTimeout(timeout time.Duration) *LedgerVatTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &LedgerVatTypeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewLedgerVatTypeSearchParamsWithContext creates a new LedgerVatTypeSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewLedgerVatTypeSearchParamsWithContext(ctx context.Context) *LedgerVatTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &LedgerVatTypeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewLedgerVatTypeSearchParamsWithHTTPClient creates a new LedgerVatTypeSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLedgerVatTypeSearchParamsWithHTTPClient(client *http.Client) *LedgerVatTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &LedgerVatTypeSearchParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*LedgerVatTypeSearchParams contains all the parameters to send to the API endpoint
for the ledger vat type search operation typically these are written to a http.Request
*/
type LedgerVatTypeSearchParams struct {

	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*ID
	  List of IDs

	*/
	ID *string
	/*Number
	  List of IDs

	*/
	Number *string
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithTimeout(timeout time.Duration) *LedgerVatTypeSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithContext(ctx context.Context) *LedgerVatTypeSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithHTTPClient(client *http.Client) *LedgerVatTypeSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithCount(count *int64) *LedgerVatTypeSearchParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetCount(count *int64) {
	o.Count = count
}

// WithFields adds the fields to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithFields(fields *string) *LedgerVatTypeSearchParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithFrom(from *int64) *LedgerVatTypeSearchParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetFrom(from *int64) {
	o.From = from
}

// WithID adds the id to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithID(id *string) *LedgerVatTypeSearchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetID(id *string) {
	o.ID = id
}

// WithNumber adds the number to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithNumber(number *string) *LedgerVatTypeSearchParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetNumber(number *string) {
	o.Number = number
}

// WithSorting adds the sorting to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) WithSorting(sorting *string) *LedgerVatTypeSearchParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the ledger vat type search params
func (o *LedgerVatTypeSearchParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WriteToRequest writes these params to a swagger request
func (o *LedgerVatTypeSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.Number != nil {

		// query param number
		var qrNumber string
		if o.Number != nil {
			qrNumber = *o.Number
		}
		qNumber := qrNumber
		if qNumber != "" {
			if err := r.SetQueryParam("number", qNumber); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
