// Code generated by go-swagger; DO NOT EDIT.

package department

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// NewDepartmentListPutListParams creates a new DepartmentListPutListParams object
// with the default values initialized.
func NewDepartmentListPutListParams() *DepartmentListPutListParams {
	var ()
	return &DepartmentListPutListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDepartmentListPutListParamsWithTimeout creates a new DepartmentListPutListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDepartmentListPutListParamsWithTimeout(timeout time.Duration) *DepartmentListPutListParams {
	var ()
	return &DepartmentListPutListParams{

		timeout: timeout,
	}
}

// NewDepartmentListPutListParamsWithContext creates a new DepartmentListPutListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDepartmentListPutListParamsWithContext(ctx context.Context) *DepartmentListPutListParams {
	var ()
	return &DepartmentListPutListParams{

		Context: ctx,
	}
}

// NewDepartmentListPutListParamsWithHTTPClient creates a new DepartmentListPutListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDepartmentListPutListParamsWithHTTPClient(client *http.Client) *DepartmentListPutListParams {
	var ()
	return &DepartmentListPutListParams{
		HTTPClient: client,
	}
}

/*DepartmentListPutListParams contains all the parameters to send to the API endpoint
for the department list put list operation typically these are written to a http.Request
*/
type DepartmentListPutListParams struct {

	/*Body
	  JSON representing updates to object. Should have ID and version set.

	*/
	Body []*models.Department

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the department list put list params
func (o *DepartmentListPutListParams) WithTimeout(timeout time.Duration) *DepartmentListPutListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the department list put list params
func (o *DepartmentListPutListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the department list put list params
func (o *DepartmentListPutListParams) WithContext(ctx context.Context) *DepartmentListPutListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the department list put list params
func (o *DepartmentListPutListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the department list put list params
func (o *DepartmentListPutListParams) WithHTTPClient(client *http.Client) *DepartmentListPutListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the department list put list params
func (o *DepartmentListPutListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the department list put list params
func (o *DepartmentListPutListParams) WithBody(body []*models.Department) *DepartmentListPutListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the department list put list params
func (o *DepartmentListPutListParams) SetBody(body []*models.Department) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DepartmentListPutListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
