// Code generated by go-swagger; DO NOT EDIT.

package department

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// NewDepartmentPostParams creates a new DepartmentPostParams object
// with the default values initialized.
func NewDepartmentPostParams() *DepartmentPostParams {
	var ()
	return &DepartmentPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDepartmentPostParamsWithTimeout creates a new DepartmentPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDepartmentPostParamsWithTimeout(timeout time.Duration) *DepartmentPostParams {
	var ()
	return &DepartmentPostParams{

		timeout: timeout,
	}
}

// NewDepartmentPostParamsWithContext creates a new DepartmentPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewDepartmentPostParamsWithContext(ctx context.Context) *DepartmentPostParams {
	var ()
	return &DepartmentPostParams{

		Context: ctx,
	}
}

// NewDepartmentPostParamsWithHTTPClient creates a new DepartmentPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDepartmentPostParamsWithHTTPClient(client *http.Client) *DepartmentPostParams {
	var ()
	return &DepartmentPostParams{
		HTTPClient: client,
	}
}

/*DepartmentPostParams contains all the parameters to send to the API endpoint
for the department post operation typically these are written to a http.Request
*/
type DepartmentPostParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.Department

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the department post params
func (o *DepartmentPostParams) WithTimeout(timeout time.Duration) *DepartmentPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the department post params
func (o *DepartmentPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the department post params
func (o *DepartmentPostParams) WithContext(ctx context.Context) *DepartmentPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the department post params
func (o *DepartmentPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the department post params
func (o *DepartmentPostParams) WithHTTPClient(client *http.Client) *DepartmentPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the department post params
func (o *DepartmentPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the department post params
func (o *DepartmentPostParams) WithBody(body *models.Department) *DepartmentPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the department post params
func (o *DepartmentPostParams) SetBody(body *models.Department) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DepartmentPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
