// Code generated by go-swagger; DO NOT EDIT.

package altinn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// CompanySettingsAltinnPutReader is a Reader for the CompanySettingsAltinnPut structure.
type CompanySettingsAltinnPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompanySettingsAltinnPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCompanySettingsAltinnPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCompanySettingsAltinnPutOK creates a CompanySettingsAltinnPutOK with default headers values
func NewCompanySettingsAltinnPutOK() *CompanySettingsAltinnPutOK {
	return &CompanySettingsAltinnPutOK{}
}

/*CompanySettingsAltinnPutOK handles this case with default header values.

successful operation
*/
type CompanySettingsAltinnPutOK struct {
	Payload *models.ResponseWrapperAltinnCompanyModule
}

func (o *CompanySettingsAltinnPutOK) Error() string {
	return fmt.Sprintf("[PUT /company/settings/altinn][%d] companySettingsAltinnPutOK  %+v", 200, o.Payload)
}

func (o *CompanySettingsAltinnPutOK) GetPayload() *models.ResponseWrapperAltinnCompanyModule {
	return o.Payload
}

func (o *CompanySettingsAltinnPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperAltinnCompanyModule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
