// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package altinn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCompanySettingsAltinnSearchParams creates a new CompanySettingsAltinnSearchParams object
// with the default values initialized.
func NewCompanySettingsAltinnSearchParams() *CompanySettingsAltinnSearchParams {
	var ()
	return &CompanySettingsAltinnSearchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCompanySettingsAltinnSearchParamsWithTimeout creates a new CompanySettingsAltinnSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCompanySettingsAltinnSearchParamsWithTimeout(timeout time.Duration) *CompanySettingsAltinnSearchParams {
	var ()
	return &CompanySettingsAltinnSearchParams{

		timeout: timeout,
	}
}

// NewCompanySettingsAltinnSearchParamsWithContext creates a new CompanySettingsAltinnSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewCompanySettingsAltinnSearchParamsWithContext(ctx context.Context) *CompanySettingsAltinnSearchParams {
	var ()
	return &CompanySettingsAltinnSearchParams{

		Context: ctx,
	}
}

// NewCompanySettingsAltinnSearchParamsWithHTTPClient creates a new CompanySettingsAltinnSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCompanySettingsAltinnSearchParamsWithHTTPClient(client *http.Client) *CompanySettingsAltinnSearchParams {
	var ()
	return &CompanySettingsAltinnSearchParams{
		HTTPClient: client,
	}
}

/*CompanySettingsAltinnSearchParams contains all the parameters to send to the API endpoint
for the company settings altinn search operation typically these are written to a http.Request
*/
type CompanySettingsAltinnSearchParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) WithTimeout(timeout time.Duration) *CompanySettingsAltinnSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) WithContext(ctx context.Context) *CompanySettingsAltinnSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) WithHTTPClient(client *http.Client) *CompanySettingsAltinnSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) WithFields(fields *string) *CompanySettingsAltinnSearchParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the company settings altinn search params
func (o *CompanySettingsAltinnSearchParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *CompanySettingsAltinnSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
