// Code generated by go-swagger; DO NOT EDIT.

package rate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new rate API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for rate API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	TravelExpenseRateGet(params *TravelExpenseRateGetParams, authInfo runtime.ClientAuthInfoWriter) (*TravelExpenseRateGetOK, error)

	TravelExpenseRateSearch(params *TravelExpenseRateSearchParams, authInfo runtime.ClientAuthInfoWriter) (*TravelExpenseRateSearchOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  TravelExpenseRateGet bs e t a get travel expense rate by ID
*/
func (a *Client) TravelExpenseRateGet(params *TravelExpenseRateGetParams, authInfo runtime.ClientAuthInfoWriter) (*TravelExpenseRateGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTravelExpenseRateGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "TravelExpenseRateGet",
		Method:             "GET",
		PathPattern:        "/travelExpense/rate/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &TravelExpenseRateGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TravelExpenseRateGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TravelExpenseRateGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  TravelExpenseRateSearch bs e t a find rates corresponding with sent data
*/
func (a *Client) TravelExpenseRateSearch(params *TravelExpenseRateSearchParams, authInfo runtime.ClientAuthInfoWriter) (*TravelExpenseRateSearchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTravelExpenseRateSearchParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "TravelExpenseRateSearch",
		Method:             "GET",
		PathPattern:        "/travelExpense/rate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &TravelExpenseRateSearchReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TravelExpenseRateSearchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TravelExpenseRateSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
