// Code generated by go-swagger; DO NOT EDIT.

package rate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// TravelExpenseRateGetReader is a Reader for the TravelExpenseRateGet structure.
type TravelExpenseRateGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TravelExpenseRateGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTravelExpenseRateGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTravelExpenseRateGetOK creates a TravelExpenseRateGetOK with default headers values
func NewTravelExpenseRateGetOK() *TravelExpenseRateGetOK {
	return &TravelExpenseRateGetOK{}
}

/*TravelExpenseRateGetOK handles this case with default header values.

successful operation
*/
type TravelExpenseRateGetOK struct {
	Payload *models.ResponseWrapperTravelExpenseRate
}

func (o *TravelExpenseRateGetOK) Error() string {
	return fmt.Sprintf("[GET /travelExpense/rate/{id}][%d] travelExpenseRateGetOK  %+v", 200, o.Payload)
}

func (o *TravelExpenseRateGetOK) GetPayload() *models.ResponseWrapperTravelExpenseRate {
	return o.Payload
}

func (o *TravelExpenseRateGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperTravelExpenseRate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
