// Code generated by go-swagger; DO NOT EDIT.

package document_archive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// DocumentArchivePutReader is a Reader for the DocumentArchivePut structure.
type DocumentArchivePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DocumentArchivePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDocumentArchivePutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDocumentArchivePutOK creates a DocumentArchivePutOK with default headers values
func NewDocumentArchivePutOK() *DocumentArchivePutOK {
	return &DocumentArchivePutOK{}
}

/*DocumentArchivePutOK handles this case with default header values.

successful operation
*/
type DocumentArchivePutOK struct {
	Payload *models.ResponseWrapperDocumentArchive
}

func (o *DocumentArchivePutOK) Error() string {
	return fmt.Sprintf("[PUT /documentArchive/{id}][%d] documentArchivePutOK  %+v", 200, o.Payload)
}

func (o *DocumentArchivePutOK) GetPayload() *models.ResponseWrapperDocumentArchive {
	return o.Payload
}

func (o *DocumentArchivePutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperDocumentArchive)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
