// Code generated by go-swagger; DO NOT EDIT.

package travel_expensezone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTravelExpenseZoneGetParams creates a new TravelExpenseZoneGetParams object
// with the default values initialized.
func NewTravelExpenseZoneGetParams() *TravelExpenseZoneGetParams {
	var ()
	return &TravelExpenseZoneGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTravelExpenseZoneGetParamsWithTimeout creates a new TravelExpenseZoneGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTravelExpenseZoneGetParamsWithTimeout(timeout time.Duration) *TravelExpenseZoneGetParams {
	var ()
	return &TravelExpenseZoneGetParams{

		timeout: timeout,
	}
}

// NewTravelExpenseZoneGetParamsWithContext creates a new TravelExpenseZoneGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewTravelExpenseZoneGetParamsWithContext(ctx context.Context) *TravelExpenseZoneGetParams {
	var ()
	return &TravelExpenseZoneGetParams{

		Context: ctx,
	}
}

// NewTravelExpenseZoneGetParamsWithHTTPClient creates a new TravelExpenseZoneGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTravelExpenseZoneGetParamsWithHTTPClient(client *http.Client) *TravelExpenseZoneGetParams {
	var ()
	return &TravelExpenseZoneGetParams{
		HTTPClient: client,
	}
}

/*TravelExpenseZoneGetParams contains all the parameters to send to the API endpoint
for the travel expense zone get operation typically these are written to a http.Request
*/
type TravelExpenseZoneGetParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) WithTimeout(timeout time.Duration) *TravelExpenseZoneGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) WithContext(ctx context.Context) *TravelExpenseZoneGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) WithHTTPClient(client *http.Client) *TravelExpenseZoneGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) WithFields(fields *string) *TravelExpenseZoneGetParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) WithID(id int32) *TravelExpenseZoneGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the travel expense zone get params
func (o *TravelExpenseZoneGetParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TravelExpenseZoneGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
