// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// OrderSearchReader is a Reader for the OrderSearch structure.
type OrderSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrderSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrderSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOrderSearchOK creates a OrderSearchOK with default headers values
func NewOrderSearchOK() *OrderSearchOK {
	return &OrderSearchOK{}
}

/*OrderSearchOK handles this case with default header values.

successful operation
*/
type OrderSearchOK struct {
	Payload *models.ListResponseOrder
}

func (o *OrderSearchOK) Error() string {
	return fmt.Sprintf("[GET /order][%d] orderSearchOK  %+v", 200, o.Payload)
}

func (o *OrderSearchOK) GetPayload() *models.ListResponseOrder {
	return o.Payload
}

func (o *OrderSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseOrder)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
