// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// NewOrderPostParams creates a new OrderPostParams object
// with the default values initialized.
func NewOrderPostParams() *OrderPostParams {
	var ()
	return &OrderPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrderPostParamsWithTimeout creates a new OrderPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrderPostParamsWithTimeout(timeout time.Duration) *OrderPostParams {
	var ()
	return &OrderPostParams{

		timeout: timeout,
	}
}

// NewOrderPostParamsWithContext creates a new OrderPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrderPostParamsWithContext(ctx context.Context) *OrderPostParams {
	var ()
	return &OrderPostParams{

		Context: ctx,
	}
}

// NewOrderPostParamsWithHTTPClient creates a new OrderPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrderPostParamsWithHTTPClient(client *http.Client) *OrderPostParams {
	var ()
	return &OrderPostParams{
		HTTPClient: client,
	}
}

/*OrderPostParams contains all the parameters to send to the API endpoint
for the order post operation typically these are written to a http.Request
*/
type OrderPostParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.Order

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the order post params
func (o *OrderPostParams) WithTimeout(timeout time.Duration) *OrderPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order post params
func (o *OrderPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order post params
func (o *OrderPostParams) WithContext(ctx context.Context) *OrderPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order post params
func (o *OrderPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order post params
func (o *OrderPostParams) WithHTTPClient(client *http.Client) *OrderPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order post params
func (o *OrderPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the order post params
func (o *OrderPostParams) WithBody(body *models.Order) *OrderPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the order post params
func (o *OrderPostParams) SetBody(body *models.Order) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *OrderPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
