// Code generated by go-swagger; DO NOT EDIT.

package mileage_allowance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bjerkio/tripletex-go/models"
)

// NewTravelExpenseMileageAllowancePutParams creates a new TravelExpenseMileageAllowancePutParams object
// with the default values initialized.
func NewTravelExpenseMileageAllowancePutParams() *TravelExpenseMileageAllowancePutParams {
	var ()
	return &TravelExpenseMileageAllowancePutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTravelExpenseMileageAllowancePutParamsWithTimeout creates a new TravelExpenseMileageAllowancePutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTravelExpenseMileageAllowancePutParamsWithTimeout(timeout time.Duration) *TravelExpenseMileageAllowancePutParams {
	var ()
	return &TravelExpenseMileageAllowancePutParams{

		timeout: timeout,
	}
}

// NewTravelExpenseMileageAllowancePutParamsWithContext creates a new TravelExpenseMileageAllowancePutParams object
// with the default values initialized, and the ability to set a context for a request
func NewTravelExpenseMileageAllowancePutParamsWithContext(ctx context.Context) *TravelExpenseMileageAllowancePutParams {
	var ()
	return &TravelExpenseMileageAllowancePutParams{

		Context: ctx,
	}
}

// NewTravelExpenseMileageAllowancePutParamsWithHTTPClient creates a new TravelExpenseMileageAllowancePutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTravelExpenseMileageAllowancePutParamsWithHTTPClient(client *http.Client) *TravelExpenseMileageAllowancePutParams {
	var ()
	return &TravelExpenseMileageAllowancePutParams{
		HTTPClient: client,
	}
}

/*TravelExpenseMileageAllowancePutParams contains all the parameters to send to the API endpoint
for the travel expense mileage allowance put operation typically these are written to a http.Request
*/
type TravelExpenseMileageAllowancePutParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.MileageAllowance
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) WithTimeout(timeout time.Duration) *TravelExpenseMileageAllowancePutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) WithContext(ctx context.Context) *TravelExpenseMileageAllowancePutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) WithHTTPClient(client *http.Client) *TravelExpenseMileageAllowancePutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) WithBody(body *models.MileageAllowance) *TravelExpenseMileageAllowancePutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) SetBody(body *models.MileageAllowance) {
	o.Body = body
}

// WithID adds the id to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) WithID(id int32) *TravelExpenseMileageAllowancePutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the travel expense mileage allowance put params
func (o *TravelExpenseMileageAllowancePutParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TravelExpenseMileageAllowancePutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
