// Code generated by go-swagger; DO NOT EDIT.

package purchase_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPurchaseOrderDeleteParams creates a new PurchaseOrderDeleteParams object
// with the default values initialized.
func NewPurchaseOrderDeleteParams() *PurchaseOrderDeleteParams {
	var ()
	return &PurchaseOrderDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPurchaseOrderDeleteParamsWithTimeout creates a new PurchaseOrderDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPurchaseOrderDeleteParamsWithTimeout(timeout time.Duration) *PurchaseOrderDeleteParams {
	var ()
	return &PurchaseOrderDeleteParams{

		timeout: timeout,
	}
}

// NewPurchaseOrderDeleteParamsWithContext creates a new PurchaseOrderDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewPurchaseOrderDeleteParamsWithContext(ctx context.Context) *PurchaseOrderDeleteParams {
	var ()
	return &PurchaseOrderDeleteParams{

		Context: ctx,
	}
}

// NewPurchaseOrderDeleteParamsWithHTTPClient creates a new PurchaseOrderDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPurchaseOrderDeleteParamsWithHTTPClient(client *http.Client) *PurchaseOrderDeleteParams {
	var ()
	return &PurchaseOrderDeleteParams{
		HTTPClient: client,
	}
}

/*PurchaseOrderDeleteParams contains all the parameters to send to the API endpoint
for the purchase order delete operation typically these are written to a http.Request
*/
type PurchaseOrderDeleteParams struct {

	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the purchase order delete params
func (o *PurchaseOrderDeleteParams) WithTimeout(timeout time.Duration) *PurchaseOrderDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the purchase order delete params
func (o *PurchaseOrderDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the purchase order delete params
func (o *PurchaseOrderDeleteParams) WithContext(ctx context.Context) *PurchaseOrderDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the purchase order delete params
func (o *PurchaseOrderDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the purchase order delete params
func (o *PurchaseOrderDeleteParams) WithHTTPClient(client *http.Client) *PurchaseOrderDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the purchase order delete params
func (o *PurchaseOrderDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the purchase order delete params
func (o *PurchaseOrderDeleteParams) WithID(id int32) *PurchaseOrderDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the purchase order delete params
func (o *PurchaseOrderDeleteParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PurchaseOrderDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
