// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package per_diem_compensation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTravelExpensePerDiemCompensationDeleteParams creates a new TravelExpensePerDiemCompensationDeleteParams object
// with the default values initialized.
func NewTravelExpensePerDiemCompensationDeleteParams() *TravelExpensePerDiemCompensationDeleteParams {
	var ()
	return &TravelExpensePerDiemCompensationDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTravelExpensePerDiemCompensationDeleteParamsWithTimeout creates a new TravelExpensePerDiemCompensationDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTravelExpensePerDiemCompensationDeleteParamsWithTimeout(timeout time.Duration) *TravelExpensePerDiemCompensationDeleteParams {
	var ()
	return &TravelExpensePerDiemCompensationDeleteParams{

		timeout: timeout,
	}
}

// NewTravelExpensePerDiemCompensationDeleteParamsWithContext creates a new TravelExpensePerDiemCompensationDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewTravelExpensePerDiemCompensationDeleteParamsWithContext(ctx context.Context) *TravelExpensePerDiemCompensationDeleteParams {
	var ()
	return &TravelExpensePerDiemCompensationDeleteParams{

		Context: ctx,
	}
}

// NewTravelExpensePerDiemCompensationDeleteParamsWithHTTPClient creates a new TravelExpensePerDiemCompensationDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTravelExpensePerDiemCompensationDeleteParamsWithHTTPClient(client *http.Client) *TravelExpensePerDiemCompensationDeleteParams {
	var ()
	return &TravelExpensePerDiemCompensationDeleteParams{
		HTTPClient: client,
	}
}

/*TravelExpensePerDiemCompensationDeleteParams contains all the parameters to send to the API endpoint
for the travel expense per diem compensation delete operation typically these are written to a http.Request
*/
type TravelExpensePerDiemCompensationDeleteParams struct {

	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) WithTimeout(timeout time.Duration) *TravelExpensePerDiemCompensationDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) WithContext(ctx context.Context) *TravelExpensePerDiemCompensationDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) WithHTTPClient(client *http.Client) *TravelExpensePerDiemCompensationDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) WithID(id int32) *TravelExpensePerDiemCompensationDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the travel expense per diem compensation delete params
func (o *TravelExpensePerDiemCompensationDeleteParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TravelExpensePerDiemCompensationDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
