// Code generated by go-swagger; DO NOT EDIT.

package accounting_period

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// LedgerAccountingPeriodSearchReader is a Reader for the LedgerAccountingPeriodSearch structure.
type LedgerAccountingPeriodSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LedgerAccountingPeriodSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLedgerAccountingPeriodSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLedgerAccountingPeriodSearchOK creates a LedgerAccountingPeriodSearchOK with default headers values
func NewLedgerAccountingPeriodSearchOK() *LedgerAccountingPeriodSearchOK {
	return &LedgerAccountingPeriodSearchOK{}
}

/*LedgerAccountingPeriodSearchOK handles this case with default header values.

successful operation
*/
type LedgerAccountingPeriodSearchOK struct {
	Payload *models.ListResponseAccountingPeriod
}

func (o *LedgerAccountingPeriodSearchOK) Error() string {
	return fmt.Sprintf("[GET /ledger/accountingPeriod][%d] ledgerAccountingPeriodSearchOK  %+v", 200, o.Payload)
}

func (o *LedgerAccountingPeriodSearchOK) GetPayload() *models.ListResponseAccountingPeriod {
	return o.Payload
}

func (o *LedgerAccountingPeriodSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseAccountingPeriod)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
