// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new document API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for document API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	DocumentContentDownloadContent(params *DocumentContentDownloadContentParams, authInfo runtime.ClientAuthInfoWriter) (*DocumentContentDownloadContentOK, error)

	DocumentGet(params *DocumentGetParams, authInfo runtime.ClientAuthInfoWriter) (*DocumentGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DocumentContentDownloadContent bs e t a get content of document given by ID
*/
func (a *Client) DocumentContentDownloadContent(params *DocumentContentDownloadContentParams, authInfo runtime.ClientAuthInfoWriter) (*DocumentContentDownloadContentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDocumentContentDownloadContentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DocumentContentDownloadContent",
		Method:             "GET",
		PathPattern:        "/document/{id}/content",
		ProducesMediaTypes: []string{"application/octet-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DocumentContentDownloadContentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DocumentContentDownloadContentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DocumentContentDownloadContent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DocumentGet bs e t a get document by ID
*/
func (a *Client) DocumentGet(params *DocumentGetParams, authInfo runtime.ClientAuthInfoWriter) (*DocumentGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDocumentGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DocumentGet",
		Method:             "GET",
		PathPattern:        "/document/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DocumentGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DocumentGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DocumentGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
