// Code generated by go-swagger; DO NOT EDIT.

package unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// ProductUnitListPutListReader is a Reader for the ProductUnitListPutList structure.
type ProductUnitListPutListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProductUnitListPutListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProductUnitListPutListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProductUnitListPutListOK creates a ProductUnitListPutListOK with default headers values
func NewProductUnitListPutListOK() *ProductUnitListPutListOK {
	return &ProductUnitListPutListOK{}
}

/*ProductUnitListPutListOK handles this case with default header values.

successful operation
*/
type ProductUnitListPutListOK struct {
	Payload *models.ListResponseProductUnit
}

func (o *ProductUnitListPutListOK) Error() string {
	return fmt.Sprintf("[PUT /product/unit/list][%d] productUnitListPutListOK  %+v", 200, o.Payload)
}

func (o *ProductUnitListPutListOK) GetPayload() *models.ListResponseProductUnit {
	return o.Payload
}

func (o *ProductUnitListPutListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseProductUnit)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
