// Code generated by go-swagger; DO NOT EDIT.

package unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewProductUnitDeleteParams creates a new ProductUnitDeleteParams object
// with the default values initialized.
func NewProductUnitDeleteParams() *ProductUnitDeleteParams {
	var ()
	return &ProductUnitDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProductUnitDeleteParamsWithTimeout creates a new ProductUnitDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProductUnitDeleteParamsWithTimeout(timeout time.Duration) *ProductUnitDeleteParams {
	var ()
	return &ProductUnitDeleteParams{

		timeout: timeout,
	}
}

// NewProductUnitDeleteParamsWithContext creates a new ProductUnitDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewProductUnitDeleteParamsWithContext(ctx context.Context) *ProductUnitDeleteParams {
	var ()
	return &ProductUnitDeleteParams{

		Context: ctx,
	}
}

// NewProductUnitDeleteParamsWithHTTPClient creates a new ProductUnitDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProductUnitDeleteParamsWithHTTPClient(client *http.Client) *ProductUnitDeleteParams {
	var ()
	return &ProductUnitDeleteParams{
		HTTPClient: client,
	}
}

/*ProductUnitDeleteParams contains all the parameters to send to the API endpoint
for the product unit delete operation typically these are written to a http.Request
*/
type ProductUnitDeleteParams struct {

	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the product unit delete params
func (o *ProductUnitDeleteParams) WithTimeout(timeout time.Duration) *ProductUnitDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the product unit delete params
func (o *ProductUnitDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the product unit delete params
func (o *ProductUnitDeleteParams) WithContext(ctx context.Context) *ProductUnitDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the product unit delete params
func (o *ProductUnitDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the product unit delete params
func (o *ProductUnitDeleteParams) WithHTTPClient(client *http.Client) *ProductUnitDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the product unit delete params
func (o *ProductUnitDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the product unit delete params
func (o *ProductUnitDeleteParams) WithID(id int32) *ProductUnitDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the product unit delete params
func (o *ProductUnitDeleteParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ProductUnitDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
