// Code generated by go-swagger; DO NOT EDIT.

package employment_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeReader is a Reader for the EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryType structure.
type EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK creates a EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK with default headers values
func NewEmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK() *EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK {
	return &EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK{}
}

/*EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK handles this case with default header values.

successful operation
*/
type EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK struct {
	Payload *models.ListResponseEmploymentType
}

func (o *EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK) Error() string {
	return fmt.Sprintf("[GET /employee/employment/employmentType/salaryType][%d] employeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK  %+v", 200, o.Payload)
}

func (o *EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK) GetPayload() *models.ListResponseEmploymentType {
	return o.Payload
}

func (o *EmployeeEmploymentEmploymentTypeSalaryTypeGetSalaryTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseEmploymentType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
