// Code generated by go-swagger; DO NOT EDIT.

package payment_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewBankReconciliationPaymentTypeSearchParams creates a new BankReconciliationPaymentTypeSearchParams object
// with the default values initialized.
func NewBankReconciliationPaymentTypeSearchParams() *BankReconciliationPaymentTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &BankReconciliationPaymentTypeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewBankReconciliationPaymentTypeSearchParamsWithTimeout creates a new BankReconciliationPaymentTypeSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBankReconciliationPaymentTypeSearchParamsWithTimeout(timeout time.Duration) *BankReconciliationPaymentTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &BankReconciliationPaymentTypeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewBankReconciliationPaymentTypeSearchParamsWithContext creates a new BankReconciliationPaymentTypeSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewBankReconciliationPaymentTypeSearchParamsWithContext(ctx context.Context) *BankReconciliationPaymentTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &BankReconciliationPaymentTypeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewBankReconciliationPaymentTypeSearchParamsWithHTTPClient creates a new BankReconciliationPaymentTypeSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBankReconciliationPaymentTypeSearchParamsWithHTTPClient(client *http.Client) *BankReconciliationPaymentTypeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &BankReconciliationPaymentTypeSearchParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*BankReconciliationPaymentTypeSearchParams contains all the parameters to send to the API endpoint
for the bank reconciliation payment type search operation typically these are written to a http.Request
*/
type BankReconciliationPaymentTypeSearchParams struct {

	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*Description
	  Containing

	*/
	Description *string
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*ID
	  List of IDs

	*/
	ID *string
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithTimeout(timeout time.Duration) *BankReconciliationPaymentTypeSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithContext(ctx context.Context) *BankReconciliationPaymentTypeSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithHTTPClient(client *http.Client) *BankReconciliationPaymentTypeSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithCount(count *int64) *BankReconciliationPaymentTypeSearchParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetCount(count *int64) {
	o.Count = count
}

// WithDescription adds the description to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithDescription(description *string) *BankReconciliationPaymentTypeSearchParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetDescription(description *string) {
	o.Description = description
}

// WithFields adds the fields to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithFields(fields *string) *BankReconciliationPaymentTypeSearchParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithFrom(from *int64) *BankReconciliationPaymentTypeSearchParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetFrom(from *int64) {
	o.From = from
}

// WithID adds the id to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithID(id *string) *BankReconciliationPaymentTypeSearchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetID(id *string) {
	o.ID = id
}

// WithSorting adds the sorting to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) WithSorting(sorting *string) *BankReconciliationPaymentTypeSearchParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the bank reconciliation payment type search params
func (o *BankReconciliationPaymentTypeSearchParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WriteToRequest writes these params to a swagger request
func (o *BankReconciliationPaymentTypeSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Description != nil {

		// query param description
		var qrDescription string
		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {
			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
