// Code generated by go-swagger; DO NOT EDIT.

package salary_type_specification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTimesheetSalaryTypeSpecificationSearchParams creates a new TimesheetSalaryTypeSpecificationSearchParams object
// with the default values initialized.
func NewTimesheetSalaryTypeSpecificationSearchParams() *TimesheetSalaryTypeSpecificationSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &TimesheetSalaryTypeSpecificationSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewTimesheetSalaryTypeSpecificationSearchParamsWithTimeout creates a new TimesheetSalaryTypeSpecificationSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTimesheetSalaryTypeSpecificationSearchParamsWithTimeout(timeout time.Duration) *TimesheetSalaryTypeSpecificationSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &TimesheetSalaryTypeSpecificationSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewTimesheetSalaryTypeSpecificationSearchParamsWithContext creates a new TimesheetSalaryTypeSpecificationSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewTimesheetSalaryTypeSpecificationSearchParamsWithContext(ctx context.Context) *TimesheetSalaryTypeSpecificationSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &TimesheetSalaryTypeSpecificationSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewTimesheetSalaryTypeSpecificationSearchParamsWithHTTPClient creates a new TimesheetSalaryTypeSpecificationSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTimesheetSalaryTypeSpecificationSearchParamsWithHTTPClient(client *http.Client) *TimesheetSalaryTypeSpecificationSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &TimesheetSalaryTypeSpecificationSearchParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*TimesheetSalaryTypeSpecificationSearchParams contains all the parameters to send to the API endpoint
for the timesheet salary type specification search operation typically these are written to a http.Request
*/
type TimesheetSalaryTypeSpecificationSearchParams struct {

	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*DateFrom
	  From and including

	*/
	DateFrom *string
	/*DateTo
	  To and excluding

	*/
	DateTo *string
	/*EmployeeID
	  Equals

	*/
	EmployeeID *int32
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithTimeout(timeout time.Duration) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithContext(ctx context.Context) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithHTTPClient(client *http.Client) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithCount(count *int64) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetCount(count *int64) {
	o.Count = count
}

// WithDateFrom adds the dateFrom to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithDateFrom(dateFrom *string) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetDateFrom(dateFrom)
	return o
}

// SetDateFrom adds the dateFrom to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetDateFrom(dateFrom *string) {
	o.DateFrom = dateFrom
}

// WithDateTo adds the dateTo to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithDateTo(dateTo *string) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetDateTo(dateTo)
	return o
}

// SetDateTo adds the dateTo to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetDateTo(dateTo *string) {
	o.DateTo = dateTo
}

// WithEmployeeID adds the employeeID to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithEmployeeID(employeeID *int32) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetEmployeeID(employeeID)
	return o
}

// SetEmployeeID adds the employeeId to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetEmployeeID(employeeID *int32) {
	o.EmployeeID = employeeID
}

// WithFields adds the fields to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithFields(fields *string) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithFrom(from *int64) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetFrom(from *int64) {
	o.From = from
}

// WithSorting adds the sorting to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) WithSorting(sorting *string) *TimesheetSalaryTypeSpecificationSearchParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the timesheet salary type specification search params
func (o *TimesheetSalaryTypeSpecificationSearchParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WriteToRequest writes these params to a swagger request
func (o *TimesheetSalaryTypeSpecificationSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.DateFrom != nil {

		// query param dateFrom
		var qrDateFrom string
		if o.DateFrom != nil {
			qrDateFrom = *o.DateFrom
		}
		qDateFrom := qrDateFrom
		if qDateFrom != "" {
			if err := r.SetQueryParam("dateFrom", qDateFrom); err != nil {
				return err
			}
		}

	}

	if o.DateTo != nil {

		// query param dateTo
		var qrDateTo string
		if o.DateTo != nil {
			qrDateTo = *o.DateTo
		}
		qDateTo := qrDateTo
		if qDateTo != "" {
			if err := r.SetQueryParam("dateTo", qDateTo); err != nil {
				return err
			}
		}

	}

	if o.EmployeeID != nil {

		// query param employeeId
		var qrEmployeeID int32
		if o.EmployeeID != nil {
			qrEmployeeID = *o.EmployeeID
		}
		qEmployeeID := swag.FormatInt32(qrEmployeeID)
		if qEmployeeID != "" {
			if err := r.SetQueryParam("employeeId", qEmployeeID); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
