// Code generated by go-swagger; DO NOT EDIT.

package salary_type_specification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TimesheetSalaryTypeSpecificationDeleteReader is a Reader for the TimesheetSalaryTypeSpecificationDelete structure.
type TimesheetSalaryTypeSpecificationDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimesheetSalaryTypeSpecificationDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewTimesheetSalaryTypeSpecificationDeleteDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewTimesheetSalaryTypeSpecificationDeleteDefault creates a TimesheetSalaryTypeSpecificationDeleteDefault with default headers values
func NewTimesheetSalaryTypeSpecificationDeleteDefault(code int) *TimesheetSalaryTypeSpecificationDeleteDefault {
	return &TimesheetSalaryTypeSpecificationDeleteDefault{
		_statusCode: code,
	}
}

/*TimesheetSalaryTypeSpecificationDeleteDefault handles this case with default header values.

successful operation
*/
type TimesheetSalaryTypeSpecificationDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the timesheet salary type specification delete default response
func (o *TimesheetSalaryTypeSpecificationDeleteDefault) Code() int {
	return o._statusCode
}

func (o *TimesheetSalaryTypeSpecificationDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /timesheet/salaryTypeSpecification/{id}][%d] TimesheetSalaryTypeSpecification_delete default ", o._statusCode)
}

func (o *TimesheetSalaryTypeSpecificationDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
