// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// ProjectCategoryPostReader is a Reader for the ProjectCategoryPost structure.
type ProjectCategoryPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectCategoryPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProjectCategoryPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectCategoryPostCreated creates a ProjectCategoryPostCreated with default headers values
func NewProjectCategoryPostCreated() *ProjectCategoryPostCreated {
	return &ProjectCategoryPostCreated{}
}

/*ProjectCategoryPostCreated handles this case with default header values.

successfully created
*/
type ProjectCategoryPostCreated struct {
	Payload *models.ResponseWrapperProjectCategory
}

func (o *ProjectCategoryPostCreated) Error() string {
	return fmt.Sprintf("[POST /project/category][%d] projectCategoryPostCreated  %+v", 201, o.Payload)
}

func (o *ProjectCategoryPostCreated) GetPayload() *models.ResponseWrapperProjectCategory {
	return o.Payload
}

func (o *ProjectCategoryPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperProjectCategory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
