// Code generated by go-swagger; DO NOT EDIT.

package travel_expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTravelExpenseAttachmentDeleteAttachmentParams creates a new TravelExpenseAttachmentDeleteAttachmentParams object
// with the default values initialized.
func NewTravelExpenseAttachmentDeleteAttachmentParams() *TravelExpenseAttachmentDeleteAttachmentParams {
	var (
		sendToInboxDefault = bool(false)
		splitDefault       = bool(false)
	)
	return &TravelExpenseAttachmentDeleteAttachmentParams{
		SendToInbox: &sendToInboxDefault,
		Split:       &splitDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewTravelExpenseAttachmentDeleteAttachmentParamsWithTimeout creates a new TravelExpenseAttachmentDeleteAttachmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTravelExpenseAttachmentDeleteAttachmentParamsWithTimeout(timeout time.Duration) *TravelExpenseAttachmentDeleteAttachmentParams {
	var (
		sendToInboxDefault = bool(false)
		splitDefault       = bool(false)
	)
	return &TravelExpenseAttachmentDeleteAttachmentParams{
		SendToInbox: &sendToInboxDefault,
		Split:       &splitDefault,

		timeout: timeout,
	}
}

// NewTravelExpenseAttachmentDeleteAttachmentParamsWithContext creates a new TravelExpenseAttachmentDeleteAttachmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewTravelExpenseAttachmentDeleteAttachmentParamsWithContext(ctx context.Context) *TravelExpenseAttachmentDeleteAttachmentParams {
	var (
		sendToInboxDefault = bool(false)
		splitDefault       = bool(false)
	)
	return &TravelExpenseAttachmentDeleteAttachmentParams{
		SendToInbox: &sendToInboxDefault,
		Split:       &splitDefault,

		Context: ctx,
	}
}

// NewTravelExpenseAttachmentDeleteAttachmentParamsWithHTTPClient creates a new TravelExpenseAttachmentDeleteAttachmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTravelExpenseAttachmentDeleteAttachmentParamsWithHTTPClient(client *http.Client) *TravelExpenseAttachmentDeleteAttachmentParams {
	var (
		sendToInboxDefault = bool(false)
		splitDefault       = bool(false)
	)
	return &TravelExpenseAttachmentDeleteAttachmentParams{
		SendToInbox: &sendToInboxDefault,
		Split:       &splitDefault,
		HTTPClient:  client,
	}
}

/*TravelExpenseAttachmentDeleteAttachmentParams contains all the parameters to send to the API endpoint
for the travel expense attachment delete attachment operation typically these are written to a http.Request
*/
type TravelExpenseAttachmentDeleteAttachmentParams struct {

	/*SendToInbox
	  Should the attachment be sent to inbox rather than deleted?

	*/
	SendToInbox *bool
	/*Split
	  If sendToInbox is true, should the attachment be split into one voucher per page?

	*/
	Split *bool
	/*TravelExpenseID
	  ID of attachment containing the attachment to delete.

	*/
	TravelExpenseID int32
	/*Version
	  Version of voucher containing the attachment to delete.

	*/
	Version *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithTimeout(timeout time.Duration) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithContext(ctx context.Context) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithHTTPClient(client *http.Client) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSendToInbox adds the sendToInbox to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithSendToInbox(sendToInbox *bool) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetSendToInbox(sendToInbox)
	return o
}

// SetSendToInbox adds the sendToInbox to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetSendToInbox(sendToInbox *bool) {
	o.SendToInbox = sendToInbox
}

// WithSplit adds the split to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithSplit(split *bool) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetSplit(split)
	return o
}

// SetSplit adds the split to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetSplit(split *bool) {
	o.Split = split
}

// WithTravelExpenseID adds the travelExpenseID to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithTravelExpenseID(travelExpenseID int32) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetTravelExpenseID(travelExpenseID)
	return o
}

// SetTravelExpenseID adds the travelExpenseId to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetTravelExpenseID(travelExpenseID int32) {
	o.TravelExpenseID = travelExpenseID
}

// WithVersion adds the version to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WithVersion(version *int32) *TravelExpenseAttachmentDeleteAttachmentParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the travel expense attachment delete attachment params
func (o *TravelExpenseAttachmentDeleteAttachmentParams) SetVersion(version *int32) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *TravelExpenseAttachmentDeleteAttachmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SendToInbox != nil {

		// query param sendToInbox
		var qrSendToInbox bool
		if o.SendToInbox != nil {
			qrSendToInbox = *o.SendToInbox
		}
		qSendToInbox := swag.FormatBool(qrSendToInbox)
		if qSendToInbox != "" {
			if err := r.SetQueryParam("sendToInbox", qSendToInbox); err != nil {
				return err
			}
		}

	}

	if o.Split != nil {

		// query param split
		var qrSplit bool
		if o.Split != nil {
			qrSplit = *o.Split
		}
		qSplit := swag.FormatBool(qrSplit)
		if qSplit != "" {
			if err := r.SetQueryParam("split", qSplit); err != nil {
				return err
			}
		}

	}

	// path param travelExpenseId
	if err := r.SetPathParam("travelExpenseId", swag.FormatInt32(o.TravelExpenseID)); err != nil {
		return err
	}

	if o.Version != nil {

		// query param version
		var qrVersion int32
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := swag.FormatInt32(qrVersion)
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
