// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// LedgerAccountGetReader is a Reader for the LedgerAccountGet structure.
type LedgerAccountGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LedgerAccountGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLedgerAccountGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLedgerAccountGetOK creates a LedgerAccountGetOK with default headers values
func NewLedgerAccountGetOK() *LedgerAccountGetOK {
	return &LedgerAccountGetOK{}
}

/*LedgerAccountGetOK handles this case with default header values.

successful operation
*/
type LedgerAccountGetOK struct {
	Payload *models.ResponseWrapperAccount
}

func (o *LedgerAccountGetOK) Error() string {
	return fmt.Sprintf("[GET /ledger/account/{id}][%d] ledgerAccountGetOK  %+v", 200, o.Payload)
}

func (o *LedgerAccountGetOK) GetPayload() *models.ResponseWrapperAccount {
	return o.Payload
}

func (o *LedgerAccountGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
