// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// LedgerAccountSearchReader is a Reader for the LedgerAccountSearch structure.
type LedgerAccountSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LedgerAccountSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLedgerAccountSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLedgerAccountSearchOK creates a LedgerAccountSearchOK with default headers values
func NewLedgerAccountSearchOK() *LedgerAccountSearchOK {
	return &LedgerAccountSearchOK{}
}

/*LedgerAccountSearchOK handles this case with default header values.

successful operation
*/
type LedgerAccountSearchOK struct {
	Payload *models.ListResponseAccount
}

func (o *LedgerAccountSearchOK) Error() string {
	return fmt.Sprintf("[GET /ledger/account][%d] ledgerAccountSearchOK  %+v", 200, o.Payload)
}

func (o *LedgerAccountSearchOK) GetPayload() *models.ListResponseAccount {
	return o.Payload
}

func (o *LedgerAccountSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
