// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// EmployeeEmploymentPostReader is a Reader for the EmployeeEmploymentPost structure.
type EmployeeEmploymentPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeeEmploymentPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewEmployeeEmploymentPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEmployeeEmploymentPostCreated creates a EmployeeEmploymentPostCreated with default headers values
func NewEmployeeEmploymentPostCreated() *EmployeeEmploymentPostCreated {
	return &EmployeeEmploymentPostCreated{}
}

/*EmployeeEmploymentPostCreated handles this case with default header values.

successfully created
*/
type EmployeeEmploymentPostCreated struct {
	Payload *models.ResponseWrapperEmployment
}

func (o *EmployeeEmploymentPostCreated) Error() string {
	return fmt.Sprintf("[POST /employee/employment][%d] employeeEmploymentPostCreated  %+v", 201, o.Payload)
}

func (o *EmployeeEmploymentPostCreated) GetPayload() *models.ResponseWrapperEmployment {
	return o.Payload
}

func (o *EmployeeEmploymentPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperEmployment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
