// Code generated by go-swagger; DO NOT EDIT.

package annual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// LedgerAnnualAccountGetReader is a Reader for the LedgerAnnualAccountGet structure.
type LedgerAnnualAccountGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LedgerAnnualAccountGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLedgerAnnualAccountGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLedgerAnnualAccountGetOK creates a LedgerAnnualAccountGetOK with default headers values
func NewLedgerAnnualAccountGetOK() *LedgerAnnualAccountGetOK {
	return &LedgerAnnualAccountGetOK{}
}

/*LedgerAnnualAccountGetOK handles this case with default header values.

successful operation
*/
type LedgerAnnualAccountGetOK struct {
	Payload *models.ResponseWrapperAnnualAccount
}

func (o *LedgerAnnualAccountGetOK) Error() string {
	return fmt.Sprintf("[GET /ledger/annualAccount/{id}][%d] ledgerAnnualAccountGetOK  %+v", 200, o.Payload)
}

func (o *LedgerAnnualAccountGetOK) GetPayload() *models.ResponseWrapperAnnualAccount {
	return o.Payload
}

func (o *LedgerAnnualAccountGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperAnnualAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
