// Code generated by go-swagger; DO NOT EDIT.

package standard_time

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// EmployeeStandardTimePutReader is a Reader for the EmployeeStandardTimePut structure.
type EmployeeStandardTimePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeeStandardTimePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEmployeeStandardTimePutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEmployeeStandardTimePutOK creates a EmployeeStandardTimePutOK with default headers values
func NewEmployeeStandardTimePutOK() *EmployeeStandardTimePutOK {
	return &EmployeeStandardTimePutOK{}
}

/*EmployeeStandardTimePutOK handles this case with default header values.

successful operation
*/
type EmployeeStandardTimePutOK struct {
	Payload *models.ResponseWrapperStandardTime
}

func (o *EmployeeStandardTimePutOK) Error() string {
	return fmt.Sprintf("[PUT /employee/standardTime/{id}][%d] employeeStandardTimePutOK  %+v", 200, o.Payload)
}

func (o *EmployeeStandardTimePutOK) GetPayload() *models.ResponseWrapperStandardTime {
	return o.Payload
}

func (o *EmployeeStandardTimePutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperStandardTime)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
