// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package occupation_code

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEmployeeEmploymentOccupationCodeSearchParams creates a new EmployeeEmploymentOccupationCodeSearchParams object
// with the default values initialized.
func NewEmployeeEmploymentOccupationCodeSearchParams() *EmployeeEmploymentOccupationCodeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &EmployeeEmploymentOccupationCodeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeeEmploymentOccupationCodeSearchParamsWithTimeout creates a new EmployeeEmploymentOccupationCodeSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeeEmploymentOccupationCodeSearchParamsWithTimeout(timeout time.Duration) *EmployeeEmploymentOccupationCodeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &EmployeeEmploymentOccupationCodeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewEmployeeEmploymentOccupationCodeSearchParamsWithContext creates a new EmployeeEmploymentOccupationCodeSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeeEmploymentOccupationCodeSearchParamsWithContext(ctx context.Context) *EmployeeEmploymentOccupationCodeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &EmployeeEmploymentOccupationCodeSearchParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewEmployeeEmploymentOccupationCodeSearchParamsWithHTTPClient creates a new EmployeeEmploymentOccupationCodeSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeeEmploymentOccupationCodeSearchParamsWithHTTPClient(client *http.Client) *EmployeeEmploymentOccupationCodeSearchParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &EmployeeEmploymentOccupationCodeSearchParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*EmployeeEmploymentOccupationCodeSearchParams contains all the parameters to send to the API endpoint
for the employee employment occupation code search operation typically these are written to a http.Request
*/
type EmployeeEmploymentOccupationCodeSearchParams struct {

	/*Code
	  Containing

	*/
	Code *string
	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*NameNO
	  Containing

	*/
	NameNO *string
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithTimeout(timeout time.Duration) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithContext(ctx context.Context) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithHTTPClient(client *http.Client) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithCode(code *string) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetCode(code *string) {
	o.Code = code
}

// WithCount adds the count to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithCount(count *int64) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetCount(count *int64) {
	o.Count = count
}

// WithFields adds the fields to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithFields(fields *string) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithFrom(from *int64) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetFrom(from *int64) {
	o.From = from
}

// WithNameNO adds the nameNO to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithNameNO(nameNO *string) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetNameNO(nameNO)
	return o
}

// SetNameNO adds the nameNO to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetNameNO(nameNO *string) {
	o.NameNO = nameNO
}

// WithSorting adds the sorting to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) WithSorting(sorting *string) *EmployeeEmploymentOccupationCodeSearchParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the employee employment occupation code search params
func (o *EmployeeEmploymentOccupationCodeSearchParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeeEmploymentOccupationCodeSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Code != nil {

		// query param code
		var qrCode string
		if o.Code != nil {
			qrCode = *o.Code
		}
		qCode := qrCode
		if qCode != "" {
			if err := r.SetQueryParam("code", qCode); err != nil {
				return err
			}
		}

	}

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.NameNO != nil {

		// query param nameNO
		var qrNameNO string
		if o.NameNO != nil {
			qrNameNO = *o.NameNO
		}
		qNameNO := qrNameNO
		if qNameNO != "" {
			if err := r.SetQueryParam("nameNO", qNameNO); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
