// Code generated by go-swagger; DO NOT EDIT.

package orderline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/v2/models"
)

// NewOrderOrderlinePostParams creates a new OrderOrderlinePostParams object
// with the default values initialized.
func NewOrderOrderlinePostParams() *OrderOrderlinePostParams {
	var ()
	return &OrderOrderlinePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrderOrderlinePostParamsWithTimeout creates a new OrderOrderlinePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrderOrderlinePostParamsWithTimeout(timeout time.Duration) *OrderOrderlinePostParams {
	var ()
	return &OrderOrderlinePostParams{

		timeout: timeout,
	}
}

// NewOrderOrderlinePostParamsWithContext creates a new OrderOrderlinePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrderOrderlinePostParamsWithContext(ctx context.Context) *OrderOrderlinePostParams {
	var ()
	return &OrderOrderlinePostParams{

		Context: ctx,
	}
}

// NewOrderOrderlinePostParamsWithHTTPClient creates a new OrderOrderlinePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrderOrderlinePostParamsWithHTTPClient(client *http.Client) *OrderOrderlinePostParams {
	var ()
	return &OrderOrderlinePostParams{
		HTTPClient: client,
	}
}

/*OrderOrderlinePostParams contains all the parameters to send to the API endpoint
for the order orderline post operation typically these are written to a http.Request
*/
type OrderOrderlinePostParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.OrderLine

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the order orderline post params
func (o *OrderOrderlinePostParams) WithTimeout(timeout time.Duration) *OrderOrderlinePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order orderline post params
func (o *OrderOrderlinePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order orderline post params
func (o *OrderOrderlinePostParams) WithContext(ctx context.Context) *OrderOrderlinePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order orderline post params
func (o *OrderOrderlinePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order orderline post params
func (o *OrderOrderlinePostParams) WithHTTPClient(client *http.Client) *OrderOrderlinePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order orderline post params
func (o *OrderOrderlinePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the order orderline post params
func (o *OrderOrderlinePostParams) WithBody(body *models.OrderLine) *OrderOrderlinePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the order orderline post params
func (o *OrderOrderlinePostParams) SetBody(body *models.OrderLine) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *OrderOrderlinePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
