// Code generated by go-swagger; DO NOT EDIT.

package orderline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PurchaseOrderOrderlineDeleteReader is a Reader for the PurchaseOrderOrderlineDelete structure.
type PurchaseOrderOrderlineDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PurchaseOrderOrderlineDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewPurchaseOrderOrderlineDeleteDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewPurchaseOrderOrderlineDeleteDefault creates a PurchaseOrderOrderlineDeleteDefault with default headers values
func NewPurchaseOrderOrderlineDeleteDefault(code int) *PurchaseOrderOrderlineDeleteDefault {
	return &PurchaseOrderOrderlineDeleteDefault{
		_statusCode: code,
	}
}

/*PurchaseOrderOrderlineDeleteDefault handles this case with default header values.

successful operation
*/
type PurchaseOrderOrderlineDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the purchase order orderline delete default response
func (o *PurchaseOrderOrderlineDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PurchaseOrderOrderlineDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /purchaseOrder/orderline/{id}][%d] PurchaseOrderOrderlineDelete default ", o._statusCode)
}

func (o *PurchaseOrderOrderlineDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
