// Code generated by go-swagger; DO NOT EDIT.

package payslip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SalaryPayslipPdfDownloadPdfReader is a Reader for the SalaryPayslipPdfDownloadPdf structure.
type SalaryPayslipPdfDownloadPdfReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SalaryPayslipPdfDownloadPdfReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSalaryPayslipPdfDownloadPdfOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSalaryPayslipPdfDownloadPdfOK creates a SalaryPayslipPdfDownloadPdfOK with default headers values
func NewSalaryPayslipPdfDownloadPdfOK() *SalaryPayslipPdfDownloadPdfOK {
	return &SalaryPayslipPdfDownloadPdfOK{}
}

/*SalaryPayslipPdfDownloadPdfOK handles this case with default header values.

successful operation
*/
type SalaryPayslipPdfDownloadPdfOK struct {
	Payload strfmt.Base64
}

func (o *SalaryPayslipPdfDownloadPdfOK) Error() string {
	return fmt.Sprintf("[GET /salary/payslip/{id}/pdf][%d] salaryPayslipPdfDownloadPdfOK  %+v", 200, o.Payload)
}

func (o *SalaryPayslipPdfDownloadPdfOK) GetPayload() strfmt.Base64 {
	return o.Payload
}

func (o *SalaryPayslipPdfDownloadPdfOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
