// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package project_activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new project activity API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for project activity API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ProjectProjectActivityDelete(params *ProjectProjectActivityDeleteParams, authInfo runtime.ClientAuthInfoWriter) error

	ProjectProjectActivityGet(params *ProjectProjectActivityGetParams, authInfo runtime.ClientAuthInfoWriter) (*ProjectProjectActivityGetOK, error)

	ProjectProjectActivityListDeleteByIds(params *ProjectProjectActivityListDeleteByIdsParams, authInfo runtime.ClientAuthInfoWriter) error

	ProjectProjectActivityPost(params *ProjectProjectActivityPostParams, authInfo runtime.ClientAuthInfoWriter) (*ProjectProjectActivityPostCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ProjectProjectActivityDelete deletes project activity
*/
func (a *Client) ProjectProjectActivityDelete(params *ProjectProjectActivityDeleteParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProjectProjectActivityDeleteParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ProjectProjectActivityDelete",
		Method:             "DELETE",
		PathPattern:        "/project/projectActivity/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ProjectProjectActivityDeleteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  ProjectProjectActivityGet finds project activity by id
*/
func (a *Client) ProjectProjectActivityGet(params *ProjectProjectActivityGetParams, authInfo runtime.ClientAuthInfoWriter) (*ProjectProjectActivityGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProjectProjectActivityGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ProjectProjectActivityGet",
		Method:             "GET",
		PathPattern:        "/project/projectActivity/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ProjectProjectActivityGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProjectProjectActivityGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ProjectProjectActivityGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ProjectProjectActivityListDeleteByIds deletes project activities
*/
func (a *Client) ProjectProjectActivityListDeleteByIds(params *ProjectProjectActivityListDeleteByIdsParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProjectProjectActivityListDeleteByIdsParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ProjectProjectActivityListDeleteByIds",
		Method:             "DELETE",
		PathPattern:        "/project/projectActivity/list",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ProjectProjectActivityListDeleteByIdsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  ProjectProjectActivityPost adds project activity
*/
func (a *Client) ProjectProjectActivityPost(params *ProjectProjectActivityPostParams, authInfo runtime.ClientAuthInfoWriter) (*ProjectProjectActivityPostCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProjectProjectActivityPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ProjectProjectActivityPost",
		Method:             "POST",
		PathPattern:        "/project/projectActivity",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json; charset=utf-8"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ProjectProjectActivityPostReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProjectProjectActivityPostCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ProjectProjectActivityPost: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
