// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// EmployeeEmploymentDetailsGetReader is a Reader for the EmployeeEmploymentDetailsGet structure.
type EmployeeEmploymentDetailsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeeEmploymentDetailsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEmployeeEmploymentDetailsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEmployeeEmploymentDetailsGetOK creates a EmployeeEmploymentDetailsGetOK with default headers values
func NewEmployeeEmploymentDetailsGetOK() *EmployeeEmploymentDetailsGetOK {
	return &EmployeeEmploymentDetailsGetOK{}
}

/*EmployeeEmploymentDetailsGetOK handles this case with default header values.

successful operation
*/
type EmployeeEmploymentDetailsGetOK struct {
	Payload *models.ResponseWrapperEmploymentDetails
}

func (o *EmployeeEmploymentDetailsGetOK) Error() string {
	return fmt.Sprintf("[GET /employee/employment/details/{id}][%d] employeeEmploymentDetailsGetOK  %+v", 200, o.Payload)
}

func (o *EmployeeEmploymentDetailsGetOK) GetPayload() *models.ResponseWrapperEmploymentDetails {
	return o.Payload
}

func (o *EmployeeEmploymentDetailsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperEmploymentDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
