// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// NewProjectListPutListParams creates a new ProjectListPutListParams object
// with the default values initialized.
func NewProjectListPutListParams() *ProjectListPutListParams {
	var ()
	return &ProjectListPutListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectListPutListParamsWithTimeout creates a new ProjectListPutListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectListPutListParamsWithTimeout(timeout time.Duration) *ProjectListPutListParams {
	var ()
	return &ProjectListPutListParams{

		timeout: timeout,
	}
}

// NewProjectListPutListParamsWithContext creates a new ProjectListPutListParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectListPutListParamsWithContext(ctx context.Context) *ProjectListPutListParams {
	var ()
	return &ProjectListPutListParams{

		Context: ctx,
	}
}

// NewProjectListPutListParamsWithHTTPClient creates a new ProjectListPutListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectListPutListParamsWithHTTPClient(client *http.Client) *ProjectListPutListParams {
	var ()
	return &ProjectListPutListParams{
		HTTPClient: client,
	}
}

/*ProjectListPutListParams contains all the parameters to send to the API endpoint
for the project list put list operation typically these are written to a http.Request
*/
type ProjectListPutListParams struct {

	/*Body
	  JSON representing updates to object. Should have ID and version set.

	*/
	Body []*models.Project

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the project list put list params
func (o *ProjectListPutListParams) WithTimeout(timeout time.Duration) *ProjectListPutListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project list put list params
func (o *ProjectListPutListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project list put list params
func (o *ProjectListPutListParams) WithContext(ctx context.Context) *ProjectListPutListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project list put list params
func (o *ProjectListPutListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project list put list params
func (o *ProjectListPutListParams) WithHTTPClient(client *http.Client) *ProjectListPutListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project list put list params
func (o *ProjectListPutListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the project list put list params
func (o *ProjectListPutListParams) WithBody(body []*models.Project) *ProjectListPutListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the project list put list params
func (o *ProjectListPutListParams) SetBody(body []*models.Project) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectListPutListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
