// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// ProjectPutReader is a Reader for the ProjectPut structure.
type ProjectPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectPutOK creates a ProjectPutOK with default headers values
func NewProjectPutOK() *ProjectPutOK {
	return &ProjectPutOK{}
}

/*ProjectPutOK handles this case with default header values.

successful operation
*/
type ProjectPutOK struct {
	Payload *models.ResponseWrapperProject
}

func (o *ProjectPutOK) Error() string {
	return fmt.Sprintf("[PUT /project/{id}][%d] projectPutOK  %+v", 200, o.Payload)
}

func (o *ProjectPutOK) GetPayload() *models.ResponseWrapperProject {
	return o.Payload
}

func (o *ProjectPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperProject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
