// Code generated by go-swagger; DO NOT EDIT.

package currency

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/tripletex-go/models"
)

// CurrencyGetReader is a Reader for the CurrencyGet structure.
type CurrencyGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CurrencyGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCurrencyGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCurrencyGetOK creates a CurrencyGetOK with default headers values
func NewCurrencyGetOK() *CurrencyGetOK {
	return &CurrencyGetOK{}
}

/*CurrencyGetOK handles this case with default header values.

successful operation
*/
type CurrencyGetOK struct {
	Payload *models.ResponseWrapperCurrency
}

func (o *CurrencyGetOK) Error() string {
	return fmt.Sprintf("[GET /currency/{id}][%d] currencyGetOK  %+v", 200, o.Payload)
}

func (o *CurrencyGetOK) GetPayload() *models.ResponseWrapperCurrency {
	return o.Payload
}

func (o *CurrencyGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperCurrency)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
