// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BankOnboardingAccessRequestDTO bank onboarding access request d t o
//
// swagger:model BankOnboardingAccessRequestDTO
type BankOnboardingAccessRequestDTO struct {

	// id
	ID int32 `json:"id,omitempty"`

	// requestee employee Id
	RequesteeEmployeeID int32 `json:"requesteeEmployeeId,omitempty"`

	// requestee name
	RequesteeName string `json:"requesteeName,omitempty"`

	// role Id
	RoleID int32 `json:"roleId,omitempty"`
}

// Validate validates this bank onboarding access request d t o
func (m *BankOnboardingAccessRequestDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BankOnboardingAccessRequestDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BankOnboardingAccessRequestDTO) UnmarshalBinary(b []byte) error {
	var res BankOnboardingAccessRequestDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
