// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobDetailDTO job detail d t o
//
// swagger:model JobDetailDTO
type JobDetailDTO struct {

	// description
	Description string `json:"description,omitempty"`

	// group
	Group string `json:"group,omitempty"`

	// job data
	JobData map[string]interface{} `json:"jobData,omitempty"`

	// jobclass
	Jobclass string `json:"jobclass,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this job detail d t o
func (m *JobDetailDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobDetailDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobDetailDTO) UnmarshalBinary(b []byte) error {
	var res JobDetailDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
