// Copyright 2020 Bjerk AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectPeriodMonthlyStatus project period monthly status
//
// swagger:model ProjectPeriodMonthlyStatus
type ProjectPeriodMonthlyStatus struct {

	// costs
	// Read Only: true
	Costs float64 `json:"costs,omitempty"`

	// date from
	// Read Only: true
	DateFrom string `json:"dateFrom,omitempty"`

	// date to
	// Read Only: true
	DateTo string `json:"dateTo,omitempty"`

	// income
	// Read Only: true
	Income float64 `json:"income,omitempty"`
}

// Validate validates this project period monthly status
func (m *ProjectPeriodMonthlyStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectPeriodMonthlyStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectPeriodMonthlyStatus) UnmarshalBinary(b []byte) error {
	var res ProjectPeriodMonthlyStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
