// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectPeriodInvoiced project period invoiced
//
// swagger:model ProjectPeriodInvoiced
type ProjectPeriodInvoiced struct {

	// sum amount
	// Read Only: true
	SumAmount float64 `json:"sumAmount,omitempty"`

	// sum amount due
	// Read Only: true
	SumAmountDue float64 `json:"sumAmountDue,omitempty"`

	// sum amount due outstanding
	// Read Only: true
	SumAmountDueOutstanding float64 `json:"sumAmountDueOutstanding,omitempty"`

	// sum amount outstanding
	// Read Only: true
	SumAmountOutstanding float64 `json:"sumAmountOutstanding,omitempty"`

	// sum amount paid
	// Read Only: true
	SumAmountPaid float64 `json:"sumAmountPaid,omitempty"`
}

// Validate validates this project period invoiced
func (m *ProjectPeriodInvoiced) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectPeriodInvoiced) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectPeriodInvoiced) UnmarshalBinary(b []byte) error {
	var res ProjectPeriodInvoiced
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
