// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReportFilterPeriod report filter period
//
// swagger:model ReportFilterPeriod
type ReportFilterPeriod struct {

	// end
	// Format: date
	End strfmt.Date `json:"end,omitempty"`

	// relative to perpendicular
	RelativeToPerpendicular *bool `json:"relativeToPerpendicular,omitempty"`

	// start
	// Format: date
	Start strfmt.Date `json:"start,omitempty"`

	// type
	Type int32 `json:"type,omitempty"`

	// version
	Version int32 `json:"version,omitempty"`
}

// Validate validates this report filter period
func (m *ReportFilterPeriod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStart(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReportFilterPeriod) validateEnd(formats strfmt.Registry) error {

	if swag.IsZero(m.End) { // not required
		return nil
	}

	if err := validate.FormatOf("end", "body", "date", m.End.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ReportFilterPeriod) validateStart(formats strfmt.Registry) error {

	if swag.IsZero(m.Start) { // not required
		return nil
	}

	if err := validate.FormatOf("start", "body", "date", m.Start.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReportFilterPeriod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportFilterPeriod) UnmarshalBinary(b []byte) error {
	var res ReportFilterPeriod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
