// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseWrapperBoolean response wrapper boolean
//
// swagger:model ResponseWrapperBoolean
type ResponseWrapperBoolean struct {

	// value
	Value *bool `json:"value,omitempty"`
}

// Validate validates this response wrapper boolean
func (m *ResponseWrapperBoolean) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseWrapperBoolean) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseWrapperBoolean) UnmarshalBinary(b []byte) error {
	var res ResponseWrapperBoolean
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
