// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebHookWrapper web hook wrapper
//
// swagger:model WebHookWrapper
type WebHookWrapper struct {

	// event
	Event string `json:"event,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// subscription Id
	SubscriptionID int32 `json:"subscriptionId,omitempty"`

	// value
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this web hook wrapper
func (m *WebHookWrapper) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebHookWrapper) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebHookWrapper) UnmarshalBinary(b []byte) error {
	var res WebHookWrapper
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
